version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: oj-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-raghavagarwal}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-I@mraghav1}
      POSTGRES_DB: ${DB_NAME:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - oj-network

  # Backend API Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: oj-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER:-raghavagarwal}
      DB_PASSWORD: ${DB_PASSWORD:-I@mraghav1}
      DB_NAME: ${DB_NAME:-postgres}
      DB_PORT: 5432
    ports:
      - "5001:5001"
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - oj-network

  # Code Execution Sandbox
  sandbox:
    build:
      context: ./Backend/Docker
      dockerfile: Dockerfile
    container_name: cpp-sandbox
    image: cpp-sandbox
    restart: "no"
    networks:
      - oj-network

  # Frontend Web Service (Using Vite's built-in dev server)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: oj-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5001/api
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - oj-network

networks:
  oj-network:
    driver: bridge

volumes:
  postgres-data: